curl https://gtoal.com/acorn/beeb/HiEdit/EDIT00.asm -o EDIT00.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT01.asm -o EDIT01.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT02.asm -o EDIT02.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT03.asm -o EDIT03.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT04.asm -o EDIT04.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT05.asm -o EDIT05.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT06.asm -o EDIT06.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT07.asm -o EDIT07.asm
curl https://gtoal.com/acorn/beeb/HiEdit/EDIT08.asm -o EDIT08.asm
curl https://gtoal.com/acorn/beeb/HiEdit/HDR8000.asm -o HDR8000.asm
curl https://gtoal.com/acorn/beeb/HiEdit/HDRB600.asm -o HDRB600.asm
curl https://gtoal.com/acorn/beeb/HiEdit/HDRB800.asm -o HDRB800.asm
